### ISSUE TITLE
How to update my ss-libev?

### ISSUE THREAD

**Issue by lotc** [EasyPi/docker-shadowsocks-libev#10]
It seems ss-libev just update to [v3.0.8](https://github.com/shadowsocks/shadowsocks-libev/releases/tag/v3.0.8).
How can I update to the version?

**Comment by vimagick** [comment]
Just released [v3.0.8][1] minutes ago.
Sorry for the delay.

[1]: https://github.com/EasyPi/docker-shadowsocks-libev/releases/tag/v3.0.8

**Comment by lotc** [comment]
It seems I need to run command `docker image pull easypi/shadowsocks-libev` once to update the ss-libev version.
Is it necessary?
