### ISSUE TITLE
shadowsocks-libev update to 3.1.0

### ISSUE THREAD

**Issue by lotc** [EasyPi/docker-shadowsocks-libev#12]
[shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev/releases/tag/v3.1.0) has just updated to `3.1.0`.
Is there a possible way to follow the latest version without modifing the `Dockerfile` ?

**Comment by vimagick** [comment]
[v3.1.0][1]

[1]: https://github.com/EasyPi/docker-shadowsocks-libev/releases/tag/v3.1.0

**Comment by vimagick** [comment]
Please pull latest images from dockerhub. :)

**Comment by lotc** [comment]
I mean... can the Dockerfile use variable like `$Version` to keep it available without updating it every version?

**Comment by vimagick** [comment]
Good idea
