### ISSUE TITLE
编译的时候出现pcre问题

### ISSUE THREAD

**Issue by burndown** [EasyPi/docker-shadowsocks-libev#13]
checking for library containing pcre_exec... no
configure: error: Cannot find pcre library. Configure --with-pcre=DIR

**Comment by vimagick** [comment]
Dockerfile (maintained) or Dockerfile.debian (unmaintained) ?

**Comment by burndown** [comment]
用的是dockerfile.arm

**Comment by vimagick** [comment]
奇怪，我可以build成功： https://hub.docker.com/r/easypi/shadowsocks-libev-arm/
