### ISSUE TITLE
Build failed on v3.1.2 and v3.1.3

### ISSUE THREAD

**Issue by lotc** [EasyPi/docker-shadowsocks-libev#16]
Can't pull from docker hub.
Just check [travis-ci](https://travis-ci.org/EasyPi/docker-shadowsocks-libev/builds/322918790), it seems that v3.1.2 can't build on it.
Would you mind take a double check?

**Comment by vimagick** [comment]
Because no output has been received in the last 10m0s (travis-ci) :cry:
I need to build image by hand, then push to docker hub.

**Comment by lotc** [comment]
Sorry to hear that, hope you can fix it soon.

**Comment by lotc** [comment]
Did you push v3.1.2 to docker hub?
I found it's still on 3.1.1.
```
user@docker:~# docker pull easypi/shadowsocks-libev
Using default tag: latest
latest: Pulling from easypi/shadowsocks-libev
Digest: sha256:d870392675fab828e89569a539807c8ffb7c84154f6f19fcfe93d9e3437173d9
Status: Image is up to date for easypi/shadowsocks-libev:latest
```
Am I missing something?

**Comment by kevmak** [comment]
I think the problem is on the alpine image, when I try to use other 3.6 alpine images to build there is no any timeout here and successful build it. But the problem happened on 3.7 either latest stable version.

**Comment by crzidea** [comment]
Any update?

**Comment by lotc** [comment]
@crzidea Just simply build it yourself and push to your own dockerhub. I made [one](https://hub.docker.com/r/lotc/shadowsocks-libev/) if you need.
But I still think you should make yourself a copy since I can't guarantee that I would keep updated.
