### ISSUE TITLE
Doesn't it support http or https proxy ?

### ISSUE THREAD

**Issue by seryte** [EasyPi/docker-shadowsocks-libev#23]
The demo only supports `socks5` and does not support `http` or `https`?

**Comment by vimagick** [comment]
It's a socks5 proxy, you can convert socks to http proxy via [polipo][1].

```
socksParentProxy = "127.0.0.1:1080"
socksProxyType = socks5
proxyAddress = "127.0.0.1"
proxyPort = 8123
```

[1]: https://www.irif.fr/~jch/software/polipo/manual/SOCKS-parent-proxies.html

**Comment by seryte** [comment]
> The demo only supports `socks5` and does not support `http` or `https`?

thanks

**Comment by vimagick** [comment]
@seryte Please try [shadowsocks-rust](https://github.com/shadowsocks/shadowsocks-rust):

```bash
$ cat config.json
{
    "server":"x.x.x.x",
    "server_port":8388,
    "local_address":"127.0.0.1",
    "local_port":3128,
    "method":"chacha20-ietf-poly1305",
    "password":"******",
    "protocol": "http",
    "timeout":60
}

$ sslocal --daemonize --config config.json

$ curl -x http://127.0.0.1:3128 https://ipinfo.io/json
```
