### ISSUE TITLE
Wanna to add workers and fast_open variable

### ISSUE THREAD

**Issue by digitaltwt** [EasyPi/docker-shadowsocks-libev#4]
I wanna to add workers and fast_open variable, Docker file as follows:
CMD ss-server -s "$SERVER_ADDR" \
              -p "$SERVER_PORT" \
              -m "$METHOD"      \
              -k "$PASSWORD"    \
              -t "$TIMEOUT"     \
              -d "$DNS_ADDR"    \
              -u                \
              --fast_open "$OPTIONS" \
              --workers "$NUM"
Docker-compose file as follows:
           environment:
                   - OPTIONS=true
                   -NUM=1

But still not work,Please help me,Thanks.

**Comment by vimagick** [comment]
Can you post the logs?

`docker-compose logs`

**Comment by digitaltwt** [comment]
server_1 |  2017-02-23 02:30:47 ERROR: Unrecognized option: (null)
server_1 | ss-server: unrecognized option: workers
server_1 |  2017-02-23 02:30:47 ERROR: Unrecognized option: (null)

**Comment by vimagick** [comment]
`ss-server` doesn't have the `--workers` option.
`shadowsocks-libev` (C) is different from `shadowsocks` (Python).

**Comment by digitaltwt** [comment]
Haha, I see, Thanks. It's my mistake.
