### ISSUE TITLE
能否把simple-obfs这个组件也编译进镜像里呢？

### ISSUE THREAD

**Issue by hkbase** [EasyPi/docker-shadowsocks-libev#6]
https://github.com/shadowsocks/simple-obfs
能否把这个组件也编译进镜像里呢？
shadowsocks-libev 3.0.3版本支持流量混淆，主要就是上面的那个插件在起作用。
谢谢啦~~~~

**Comment by liaohuqiu** [comment]
我这有一个 https://github.com/liaohuqiu/docker-simple-obfs

**Comment by vimagick** [comment]
该组件尚未成熟, 过段时间再集成.
另外, 可以使用link的方式来使用.

**Comment by hkbase** [comment]
非常期待大神发布集成simple-obfs的SS镜像~，由衷的感谢~~

**Comment by wd** [comment]
Fork 了一个，把 @liaohuqiu  dockerfile 合并到了这个，然后重新 build 一下就可以了。https://github.com/wd/docker-shadowsocks-libev

希望作者能考虑下直接加到这个镜像里面。

**Comment by vimagick** [comment]
重新写一个Dockerfile.obfs, 把`easypi/shadowsocks-libev`作为base image更好。

```
FROM easypi/shadowsocks-libev
```

并且build出一个新的image: `easypi/shadowsocks-libev:obfs`

**Comment by Primovist** [comment]
可以看看我的。

**Comment by Primovist** [comment]
primovist/shadowsocks-libev.simple-obfs
Docker和GitHub同名。
