### ISSUE TITLE
Failed to build Dockerfile.debian

### ISSUE THREAD

**Issue by lotc** [EasyPi/docker-shadowsocks-libev#8]
when I try to `docker build` the debian version, it shows error as below.
``` The following packages have unmet dependencies:
 dh-systemd : Depends: debhelper but it is not going to be installed
 libssl-dev : Depends: libssl1.0.0 (= 1.0.1t-1+deb8u6) but 1.0.2k-1~bpo8+1 is to be installed
              Recommends: libssl-doc but it is not going to be installed
E: Unable to correct problems, you have held broken packages. 
```
Which results the following output: ` returned a non-zero code: 100 `

**Comment by vimagick** [comment]
I'll fix it as soon as Debian 9 (Stretch) be released.

**Comment by lotc** [comment]
Seems `ubuntu:16.10` has `libsodium-dev` `libmbedtls-dev` on apt repo, which means that you don't have to build them via source code.
